//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rocio.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class FontList : global::System.Configuration.ApplicationSettingsBase {
        
        private static FontList defaultInstance = ((FontList)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FontList())));
        
        public static FontList Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F1 {
            get {
                return ((global::System.Drawing.Font)(this["F1"]));
            }
            set {
                this["F1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F2 {
            get {
                return ((global::System.Drawing.Font)(this["F2"]));
            }
            set {
                this["F2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F3 {
            get {
                return ((global::System.Drawing.Font)(this["F3"]));
            }
            set {
                this["F3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F4 {
            get {
                return ((global::System.Drawing.Font)(this["F4"]));
            }
            set {
                this["F4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F5 {
            get {
                return ((global::System.Drawing.Font)(this["F5"]));
            }
            set {
                this["F5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F6 {
            get {
                return ((global::System.Drawing.Font)(this["F6"]));
            }
            set {
                this["F6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F7 {
            get {
                return ((global::System.Drawing.Font)(this["F7"]));
            }
            set {
                this["F7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F8 {
            get {
                return ((global::System.Drawing.Font)(this["F8"]));
            }
            set {
                this["F8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F9 {
            get {
                return ((global::System.Drawing.Font)(this["F9"]));
            }
            set {
                this["F9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F10 {
            get {
                return ((global::System.Drawing.Font)(this["F10"]));
            }
            set {
                this["F10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F11 {
            get {
                return ((global::System.Drawing.Font)(this["F11"]));
            }
            set {
                this["F11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font F12 {
            get {
                return ((global::System.Drawing.Font)(this["F12"]));
            }
            set {
                this["F12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F1Color {
            get {
                return ((global::System.Drawing.Color)(this["F1Color"]));
            }
            set {
                this["F1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F2Color {
            get {
                return ((global::System.Drawing.Color)(this["F2Color"]));
            }
            set {
                this["F2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F3Color {
            get {
                return ((global::System.Drawing.Color)(this["F3Color"]));
            }
            set {
                this["F3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F4Color {
            get {
                return ((global::System.Drawing.Color)(this["F4Color"]));
            }
            set {
                this["F4Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F5Color {
            get {
                return ((global::System.Drawing.Color)(this["F5Color"]));
            }
            set {
                this["F5Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F6Color {
            get {
                return ((global::System.Drawing.Color)(this["F6Color"]));
            }
            set {
                this["F6Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F7Color {
            get {
                return ((global::System.Drawing.Color)(this["F7Color"]));
            }
            set {
                this["F7Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F8Color {
            get {
                return ((global::System.Drawing.Color)(this["F8Color"]));
            }
            set {
                this["F8Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F9Color {
            get {
                return ((global::System.Drawing.Color)(this["F9Color"]));
            }
            set {
                this["F9Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F10Color {
            get {
                return ((global::System.Drawing.Color)(this["F10Color"]));
            }
            set {
                this["F10Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F11Color {
            get {
                return ((global::System.Drawing.Color)(this["F11Color"]));
            }
            set {
                this["F11Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color F12Color {
            get {
                return ((global::System.Drawing.Color)(this["F12Color"]));
            }
            set {
                this["F12Color"] = value;
            }
        }
    }
}
